// Comprehensive dataset of Gujarat Cities and Districts
export const GUJARAT_CITIES = [
  'Ahmedabad',
  'Amreli',
  'Anand',
  'Ankleshwar',
  'Aravalli',
  'Banaskantha',
  'Bharuch',
  'Bhavnagar',
  'Kutch',
  'Botad',
  'Chhota Udaipur',
  'Dahod',
  'Dang',
  'Dwarka',
  'Gandhinagar',
  'Gir Somnath',
  'Panchmahal',
  'Himmatnagar',
  'Jamnagar',
  'Junagadh',
  'Kheda',
  'Mahisagar',
  'Mehsana',
  'Morbi',
  'Navsari',
  'Patan',
  'Porbandar',
  'Rajkot',
  'Sabarkantha',
  'Surat',
  'Surendranagar',
  'Tapi',
  'Vadodara',
  'Valsad',
];
